### ISSUE TITLE
I tried it :)

### ISSUE THREAD

**Issue by timfenney** [sum-rock/just-sum-nix#127]
Thanks, looks 🔥🔥

I fired up the 22.11 VBox appliance and gave it a shot, running the following command:

$ nix build nixpkgs\#nixosConfigurations.`hostname`.system --experimental-features 'nix-command flakes'

but I get the error:

error: flake 'flake:nixpkgs' does not provide attribute 'packages.x86_64-linux.nixosConfigurations.nixos.system', 'legacyPackages.x86_64-linux.nixosConfigurations.nixos.system' or 'nixosConfigurations.nixos.system'

Is there something I'm missing?

**Comment by timfenney** [comment]
Wow, thanks for responding!

Looks like the VBox Appliance has some different config:

```
{ config, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/virtualbox-demo.nix> ];
}
```
I don't know what branch corresponds to the latest 22.11, maybe this is the right branch representing what I have:
https://github.com/NixOS/nixpkgs/blob/backport-140890-to-release-22.11/nixos/modules/installer/virtualbox-demo.nix

The only option you suggested which seems to work ok is:
```
nixpkgs.config.allowUnfree = true;
```
With the experimental features set as per the readme, I get:
```
uilding Nix...
building the system configuration...
these 6 derivations will be built:
  /nix/store/d1yjd3l14wjp2k8mqk5rcccz5iw6ja9k-unit-console-getty.service-disabled.drv
  /nix/store/c2rpki52lbc9gzbpqfk0l09d8r3qgq9z-nix.conf.drv
  /nix/store/khgxad273bvma9yxr3k098ssvyygc132-unit-nix-daemon.service.drv
  /nix/store/7l2vhvpfjv5bhjvx74yxvk0mw316rhfx-system-units.drv
  /nix/store/qcx62k1pwv483k1ifgrjilwn19pl5179-etc.drv
  /nix/store/4jx65aif803f9k0428iv14gwqy5dr5h1-nixos-system-nixos-22.11.2203.285b3ff0660.drv
building '/nix/store/c2rpki52lbc9gzbpqfk0l09d8r3qgq9z-nix.conf.drv'...
building '/nix/store/d1yjd3l14wjp2k8mqk5rcccz5iw6ja9k-unit-console-getty.service-disabled.drv'...
Validating generated nix.conf
error: unknown experimental feature 'flake'
error: builder for '/nix/store/c2rpki52lbc9gzbpqfk0l09d8r3qgq9z-nix.conf.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/qcx62k1pwv483k1ifgrjilwn19pl5179-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4jx65aif803f9k0428iv14gwqy5dr5h1-nixos-system-nixos-22.11.2203.285b3ff0660.drv' failed to build
```
With all 3 lines, I get:

```
error: The option `networking.hostname' does not exist. Definition values:
       - In `/etc/nixos/configuration.nix': "nixos"
(use '--show-trace' to show detailed location information)
building Nix...
error: The option `networking.hostname' does not exist. Definition values:
       - In `/etc/nixos/configuration.nix': "nixos"
(use '--show-trace' to show detailed location information)
building the system configuration...
error: The option `networking.hostname' does not exist. Definition values:
       - In `/etc/nixos/configuration.nix': "nixos"
(use '--show-trace' to show detailed location information)
```
Here is the full file:
```
{ config, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/virtualbox-demo.nix> ];

  # Let demo build as a trusted user.
# nix.settings.trusted-users = [ "demo" ];

# Mount a VirtualBox shared folder.
# This is configurable in the VirtualBox menu at
# Machine / Settings / Shared Folders.
# fileSystems."/mnt" = {
#   fsType = "vboxsf";
#   device = "nameofdevicetomount";
#   options = [ "rw" ];
# };

# By default, the NixOS VirtualBox demo image includes SDDM and Plasma.
# If you prefer another desktop manager or display manager, you may want
# to disable the default.
# services.xserver.desktopManager.plasma5.enable = lib.mkForce false;
# services.xserver.displayManager.sddm.enable = lib.mkForce false;

# Enable GDM/GNOME by uncommenting above two lines and two lines below.
# services.xserver.displayManager.gdm.enable = true;
# services.xserver.desktopManager.gnome.enable = true;

# Set your time zone.
# time.timeZone = "Europe/Amsterdam";

# List packages installed in system profile. To search, run:
# \$ nix search wget
# environment.systemPackages = with pkgs; [
#   wget vim
# ];

# Enable the OpenSSH daemon.
# services.openssh.enable = true;

networking.hostname = "nixos";
nixpkgs.config.allowUnfree = true;
nix.settings.experimental-features = [ "nix-command" "flake" ];
}
```

**Comment by timfenney** [comment]
But don't worry too much about the VBox Appliance on my account, I was actually trying to try things out in a VM to ensure they would have the desired effect on my own hardware. It seems the systems are significantly different such that the VM is not useful to me.

I will try your instructions in a different installation :D

**Comment by sum-rock** [comment]
Yeah I'm curious about the VBox. I don't use desktop virtualization but it seems like maybe they don't have a hostname? I bet you could work around the hostname issue but what is more of a blocker is that the `error: unknown experimental feature 'flake'` error. If you can't enable flakes, its a non-starter.

A VM is certainly doable. What type of VM are you going to use, if you don't mind me asking? I've been eager to try [nix-infect](https://github.com/elitak/nixos-infect) on a digital ocean droplet. In fact, I might try right now.

**Comment by timfenney** [comment]
> Yeah I'm curious about the VBox. I don't use desktop virtualization but it seems like maybe they don't have a hostname? I bet you could work around the hostname issue but what is more of a blocker is that the `error: unknown experimental feature 'flake'` error. If you can't enable flakes, its a non-starter.

I didn't run into any problems with the switch command due to missing hostname, and I was able to enable the experimental feature with this command:
```
$ nix build nixpkgs\#nixosConfigurations.`hostname`.system --experimental-features 'nix-command flakes'
```

> A VM is certainly doable. What type of VM are you going to use, if you don't mind me asking?

I installed VirtualBox because the Appliance was supplied as a download option. I have seen yout00bers use VBox to demo NixOS installation and configuration, and now that I have it, I might as well continue with it. Unfortunately there is some problem with Guest Additions it seems, as USB needs to be disabled before booting the VM.

> I've been eager to try [nixos-infect](https://github.com/elitak/nixos-infect) on a digital ocean droplet. In fact, I might try right now.
> ### Results!

Now that's pod racing!
Time to throw up a couple tutorial videos and become independently wealthy as a DO affiliate!

**Comment by sum-rock** [comment]
I saw you had used that 'nix build' command in your first message. Now maybe I've done something wrong to cause that to not work, but I've never been able to use 'nix build' with a flake. I always get that same error you encountered. That's not just the case on this flake but it's also true for nix development environments that I've used. Typically, I'll use direnv to shim nix shell dependencies to the terminal session but if I want to just start a nix shell from a flake, I use the 'nix develop' command instead of 'nix build'. 

Unfortunately, to use the '--flake' option on the 'nixos-rebuild' command, I believe that flakes need to already be enabled. You might want to try to enable them in the '.config/nix/nix.conf' file if you're still attempting virtual box. 

I don't know man, Nix still has many mysteries for me to figure out. Stick with it though, it pays off!

**Comment by sum-rock** [comment]
@Loungagna thanks for digging in and being willing to check it out. I'm happy to help you out here, lets take a look at a few pieces of your issue one at a time. 

### i3 Desktop

You've found my Achilles heel! I've been meaning to remove that module from the repo because it just doesn't work quite right. I may dedicate more time and effort into that at a later date but it should be removed for now because it has too many issues.

### Multiple Generations

I'm not entirely sure what you mean by this. Maybe this is referring to when you didn't have it installed on NixOS? Make sure you're on the master branch with the latest commits. I __try__ to only merge to master when the branch is entirely functional (you know, like real software) but I don't always get it right the first time.

### Build and boot dir issue

This message is actually encouraging because ti means that your far enough into the build that things are happening. I am strongly suspicious that the flake is importing the wrong `hardware-configuration.nix` file. 

I might be asking a silly question but I want to make sure we're covering the basics here. `$HOST` is a stand-in for your devices hostname. For example, if your hostname is "my-computer" and your user name is "this-guy" the path to your host configurations will be `/home/this-guy/.nixpkgs/hosts/my-computer`. 

Within that directory you should have a `default.nix` that probably looks similar to the other `default.nix` files in the hosts subdirectory. You want to make sure it has the boot loader configurations that were set up in your `configuration.nix` generated on NixOs install. It's not a good idea to copy the values from the other host `default.nix` files. Many of the values will be specific to your machine.

One other thing you might try is rebooting your machine and then running the `sudo nixos-rebuild boot --flake ~/.nixpkgs#` again. 

### Next steps

Please let me know if these steps fix your issue or if you continue to have problems. In the event you're still having trouble, if you could show me your file paths with the new host directory (a screen shot or something), and the contents of your `default.nix` file in the `hosts` directory.

Alternatively, if you either fork the repository or push it to your own remote, I can probably help you much more expeditiously.

**Comment by sum-rock** [comment]
When you enter sudo nixo-rebuild and include any arguments (other than --flake) you are building the system from your /etc/nixos/configuration.nix file. When you add the --flake option with the given path you are telling NixOS to build from the flake in ~/.nixpkgs. That's why when you don't include the option, none of the packages are installing.

Your issue may be that you're trying to do to much at once. Nix is best done with lots of little changes. Let's assert some reality before moving on. 

- Are you able to add packages to your configuration.nix in the /etc/nixos directory, then enter sudo nixos-rebuild switch and have those new packages installed?
- Are you able to reboot and have your system in it's most recent state?
- Did you perform a graphical installation of NixOS?
- Does your host name share the same name with another directory in ~/.nixpkgs/hosts ?
- Are you importing your hardware configuration at the top of you ~/.nixpkgs/hosts/default.nix file?
